const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');
const src=fs.readFileSync(path.join(__dirname,'../../abastecer/app.v2.7.js'),'utf8').replace(/^<script>\s*/,'').replace(/<\/script>\s*$/,'');
function env(){const nodes={};const node=id=>nodes[id]??=(function(){const classes=new Set(['hidden']);return {id,value:'',textContent:'',innerHTML:'',disabled:false,options:[],events:{},style:{},firstElementChild:{style:{}},classList:{add:x=>classes.add(x),remove:x=>classes.delete(x),contains:x=>classes.has(x),toggle(x,v){if(v??!classes.has(x))classes.add(x);else classes.delete(x);}},addEventListener(n,f){this.events[n]=f;},appendChild(){},replaceChildren(){},querySelector(){return node('child');},removeAttribute(a){delete this[a];},focus(){},select(){},setCustomValidity(){},click(){},getContext(){return new Proxy({measureText:t=>({width:String(t).length*18})},{get:(o,k)=>o[k]||(()=>{})});},toBlob(f){f({});}};})();
const outbox=new Map(),drafts=new Map(),calls=[];let serverFn=async()=>({});const bridge={};
const sandbox={testBridge:bridge,console,URL,Date,File:class {},navigator:{onLine:true},crypto:{randomUUID:()=> 'uuid_12345678901234567890'},window:{scrollTo(){}},sessionStorage:{getItem(){return '';},setItem(){},removeItem(){}},Option:class{},addEventListener(){},setTimeout(){return 1;},clearTimeout(){},document:{getElementById:node,querySelectorAll:()=>[],createElement:()=>node('canvas')},hooks:{server:async(n,p)=>{calls.push(n);return serverFn(n,p);},banco:async(store,mode,op)=>{const m=store==='outbox'?outbox:drafts;return op({get:k=>m.get(k),getAll:()=>[...m.values()],put:v=>{m.set(store==='outbox'?v.auditoriaId:v.key,structuredClone(v));},delete:k=>m.delete(k)});}}};
const injection=`server=hooks.server;banco=hooks.banco;Object.assign(testBridge,{state,salvar,sincronizarPendentes,compartilharPedido,validarQuantidadesTela,limparOperador,atualizarProgresso,restaurarRascunho,quebrarTexto,criarImagemPedido,iniciarCameraSelfie,fecharCamera,finalizarLocalPeloOperador,atualizarLocal,checkin});`;
vm.runInNewContext(src.replace('network();boot();',injection),sandbox);
Object.assign(bridge.state,{config:{catalogo:{Bar:{Esquerda:[]}},metasLocais:{}},sessionToken:'token',operador:'Leo',selfie:'jpeg',local:'Bar',geladeira:'Esquerda',rodadaId:'round_1234567890123456',rodadaLocal:'Bar',auditoriaId:'audit_123456789012345',itens:[{skuId:'AGUA',produto:'Água',contado_humano:20}],comprovanteAnalise:'signed',progresso:{total:1,concluidas:0,equipamentos:['Esquerda'],auditadas:[],faltantes:['Esquerda']}});node('locationSelect').value='Bar';
const progress=()=>({total:1,concluidas:1,equipamentos:['Esquerda'],auditadas:['Esquerda'],faltantes:[]});
const pedido=()=>({solicitacaoId:'SOL-123',local:'Bar',operador:'Leo',criadoEm:'2026-09-07T12:00:00Z',equipamentosAuditados:['Esquerda'],itens:[{produto:'Água',quantidadeSolicitada:60}],totalUnidades:60});
return {b:bridge,nodes,node,outbox,drafts,calls,sandbox,progress,pedido,setServer:f=>serverFn=f};}
test('última geladeira salva exige confirmação explícita do pedido',async()=>{const e=env();let fail=true;e.setServer(async n=>{if(n==='salvarAuditoria')return {progresso:e.progress(),prontoParaFinalizar:true};if(n==='consultarRodada')return {encontrada:true,progresso:e.progress()};if(n==='finalizarRodada'){if(fail)throw Error('falha de rede');return e.pedido();}});await e.b.salvar();assert.equal(e.outbox.size,0);assert.equal(e.b.state.itens.length,0);await e.node('nextAudit').events.click();assert.equal(e.node('finishLocal').classList.contains('hidden'),false);fail=false;await e.b.sincronizarPendentes();assert.equal(e.b.state.solicitacao,null);assert.equal(e.calls.includes('finalizarRodada'),false);assert.equal(e.calls.filter(x=>x==='salvarAuditoria').length,1);});
test('offline guarda contagem antes de limpar tela e sincroniza ao reconectar',async()=>{const e=env();e.sandbox.navigator.onLine=false;await e.b.salvar();assert.equal(e.outbox.size,1);assert.equal(e.calls.length,0);assert.equal(e.b.state.itens.length,0);e.sandbox.navigator.onLine=true;e.setServer(async n=>n==='salvarAuditoria'?{progresso:e.progress()}:n==='consultarRodada'?{encontrada:true,progresso:e.progress()}:e.pedido());await e.b.sincronizarPendentes();assert.equal(e.outbox.size,0);assert.equal(e.b.state.solicitacao,null);assert.equal(e.calls.includes('finalizarRodada'),false);});
test('duas sincronizações simultâneas não enviam a fila em paralelo',async()=>{const e=env();e.outbox.set('old',{auditoriaId:'old',rodadaId:'another_round',operador:'Leo',criadoEm:1,payload:{}});let release;const wait=new Promise(r=>release=r);e.setServer(async n=>{if(n==='salvarAuditoria'){await wait;return {progresso:e.progress()};}return {encontrada:false};});const a=e.b.sincronizarPendentes();await Promise.resolve();const b=e.b.sincronizarPendentes();release();await Promise.all([a,b]);assert.equal(e.calls.filter(x=>x==='salvarAuditoria').length,1);assert.equal(e.b.state.progresso.concluidas,0);});
test('quantidade inválida não é enviada nem substituída silenciosamente por zero',async()=>{const e=env();e.b.state.itens[0].contado_humano='';await e.b.salvar();assert.equal(e.calls.length,0);assert.equal(e.outbox.size,0);});
test('recusa de Web Share apresenta WhatsApp e texto sem marcar envio',async()=>{const e=env();e.b.state.solicitacao=e.pedido();e.sandbox.navigator.share=async()=>{throw Object.assign(Error('blocked'),{name:'NotAllowedError'});};await e.b.compartilharPedido();assert.equal(e.node('shareFallback').classList.contains('hidden'),false);assert.match(e.node('whatsappLink').href,/wa.me/);assert.equal(e.calls.length,0);});
test('troca de auditor remove imagens do DOM e comprovante anterior',async()=>{const e=env();e.b.state.rodadaId='';e.node('selfieImage').src='old';e.node('userThumb').src='old';await e.b.limparOperador();assert.equal(e.node('selfieImage').src,undefined);assert.equal(e.node('userThumb').src,undefined);assert.equal(e.b.state.comprovanteAnalise,'');});

test('renovação de sessão preserva a rodada mesmo exigindo selfie nova',async()=>{const e=env();e.drafts.set('current',{key:'current',updatedAt:Date.now(),operador:'Leo',selfie:'old',rodadaId:'rodada_pendente_1234',rodadaLocal:'Bar',local:'Bar',geladeira:'Esquerda',fotos:['foto-original'],auditoriaId:'audit_pendente',itens:[{skuId:'AGUA',contado_humano:20}],comprovanteAnalise:'recibo',progresso:e.progress()});e.node('operatorSelect').options=[{value:'Leo'}];await e.b.restaurarRascunho(false);assert.equal(e.b.state.selfie,null);assert.equal(e.b.state.rodadaId,'rodada_pendente_1234');assert.equal(e.b.state.fotos[0],'foto-original');e.b.state.selfie='new';await e.b.restaurarRascunho(true);assert.equal(e.b.state.selfie,'new');});

// Riscos da interface: SKU truncado no pedido e câmera aberta após fechar o modal.
test('imagem mantém nome completo e aumenta altura quando o SKU exige várias linhas',async()=>{const e=env();e.b.state.solicitacao=e.pedido();await e.b.criarImagemPedido();const inicial=e.node('canvas').height;const nome='Água Mineral Natural Sem Gás Garrafa Retornável 510 ml embalagem especial do estoque central';e.b.state.solicitacao.itens[0].produto=nome;const ctx={measureText:t=>({width:t.length*18})};const linhas=e.b.quebrarTexto(ctx,nome,780);assert.equal(linhas.join(' '),nome);assert.ok(linhas.length>1);e.b.state.solicitacao.itens=Array.from({length:8},()=>({produto:nome,quantidadeSolicitada:15}));await e.b.criarImagemPedido();assert.ok(e.node('canvas').height>inicial);});
test('fechar modal durante a permissão encerra stream tardio sem reabrir a câmera',async()=>{const e=env();let resolve,stops=0;const stream={getTracks:()=>[{stop(){stops++;}}]};e.sandbox.navigator.mediaDevices={getUserMedia:()=>new Promise(r=>resolve=r)};const p=e.b.iniciarCameraSelfie();e.b.fecharCamera();resolve(stream);await p;assert.equal(stops,1);assert.equal(e.b.state.cameraStream,null);assert.equal(e.node('selfieVideo').srcObject,null);});
test('permissão de câmera negada não dispara uma segunda solicitação',async()=>{const e=env();let calls=0;e.sandbox.navigator.mediaDevices={getUserMedia:async()=>{calls++;throw Object.assign(Error('negada'),{name:'NotAllowedError'});}};await e.b.iniciarCameraSelfie();assert.equal(calls,1);assert.equal(e.node('takeSelfie').disabled,true);});

test('troca de auditor durante interrupção guarda rascunho e mantém fila sem bloquear novo turno',async()=>{
 const e=env();e.outbox.set('old',{auditoriaId:'old',operador:'Leo',local:'Bar',payload:{}});e.b.state.fotos=['foto'];await e.b.limparOperador();assert.equal(e.b.state.sessionToken,'');assert.equal(e.outbox.size,1);assert.equal(e.drafts.get('operador:leo').fotos[0],'foto');assert.equal(e.node('checkinScreen').classList.contains('hidden'),false);
});
