"""Accessible, situation-based companion generated from the same five-step source."""
from pathlib import Path
from html import escape as e
import json,sys

def build_online(d):
 data=json.loads((d/'conteudo.json').read_text());v=data['version'];parts=[]
 for i,s in enumerate(data['slides'],1):
  table=''
  if 'table' in s:
   table='<table>'+''.join('<tr>'+''.join(f'<{ "th" if ri==0 else "td"}>{e(c)}</{ "th" if ri==0 else "td"}>' for c in row)+'</tr>' for ri,row in enumerate(s['table']))+'</table>'
  illustration=f'<img class="illustration" src="{s["image"]}" alt="" width="400" height="260" loading="lazy">' if 'image' in s else ''
  parts.append(f'<section class="step searchable" id="passo-{i}"><p class="eyebrow">PASSO {i} DE 5</p><h2>{e(s["title"])}</h2><p>{e(s["subtitle"])}</p>{illustration}{table}'+(f'<p class="note">{e(s["formula"])}</p>' if 'formula' in s else '')+'<ol>'+''.join('<li>'+e(t)+'</li>' for t in s['steps'])+'</ol><p class="note">'+e(s['note'])+'</p>'+ (f'<a href="#passo-{i+1}">Próximo passo →</a>' if i<5 else '<a class="primary" href="/abastecer/">Abrir o app</a>')+'</section>')
 faqs=[('pausa','Preciso sair ou atender uma ligação','Use “Pausar e trocar de operador”. Seu rascunho fica no aparelho. Outra pessoa pode contar com o próprio nome. Para retomar, use seu nome no mesmo aparelho e endereço.'),('rede','A internet caiu','“Contagem guardada” significa que ainda falta enviar. Mantenha o rascunho e retome com conexão. Só o que foi confirmado e salvo entra no estoque do local.'),('posicao','A água está em outra geladeira','Conte onde ela está. O app soma o mesmo produto em todos os equipamentos do local antes de calcular o que falta.'),('nova','Duas pessoas contaram a mesma geladeira','Vale a foto mais recente, conferida e salva. Um envio atrasado de uma foto antiga não substitui a foto mais nova.'),('foto','A foto ou a IA não ficou boa','Use “Refazer” quando a foto não mostrar bem os produtos. Se a IA estiver indisponível, preserve o rascunho e tente novamente com conexão. Não confirme uma quantidade sem conferir.'),('envio','Como sei que o estoque recebeu?','Abrir o WhatsApp não envia sozinho. Escolha o grupo, envie e peça a confirmação. Se o compartilhamento falhar, use “Copiar texto” ou “Salvar imagem”.')]
 faq=''.join(f'<details class="searchable" id="{key}"><summary>{e(q)}</summary><p>{e(a)}</p></details>' for key,q,a in faqs)
 page=f'''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#00405a"><title>Como usar • Embaixada Carioca</title><link rel="stylesheet" href="online.css"><script src="online.js" defer></script></head><body><header><a href="/abastecer/">← Voltar ao app</a><span>Guia {v}</span></header><main><div class="intro"><img class="logo" src="../../logo.svg" width="64" height="64" alt="Embaixada Carioca"><h1>Como usar</h1><p>Fotografe, confira e peça só o que falta no local.</p><p>Leia antes do primeiro uso ou vá direto à sua dúvida.</p><label for="busca">O que você precisa?</label><input id="busca" type="search" placeholder="Ex.: internet, pausa, WhatsApp" autocomplete="off"><p id="searchStatus" role="status" hidden></p><nav aria-label="Ir direto ao passo">'''+''.join(f'<a href="#passo-{i}">{i}. {e(s["title"])}</a>' for i,s in enumerate(data['slides'],1))+'''</nav><a href="#duvidas">Resolver uma dúvida ↓</a></div>'''+''.join(parts)+f'''<section id="duvidas"><h2>Durante o turno</h2>{faq}</section><footer><h2>Leia antes de começar</h2><p>O PDF tem os 5 passos, exemplos e cuidados para usar o app. Baixe uma vez para ler sem internet ou enviar à equipe.</p><a class="primary" href="Manual-Embaixada-Carioca-{v}.pdf" download>Baixar guia para WhatsApp</a><a href="Manual-Embaixada-Carioca-{v}.pptx">Apresentação editável</a><a href="../">Ver versão atual</a></footer></main></body></html>'''
 (d/'index.html').write_text(page)
 css='''*{box-sizing:border-box}html{scroll-behavior:smooth;scroll-padding-top:76px}body{margin:0;background:#e9dfcd;color:#00405a;font:1.05rem/1.55 system-ui,sans-serif}header{position:sticky;top:0;z-index:2;display:flex;align-items:center;justify-content:space-between;gap:8px;padding:6px 16px;background:#00405a;color:#fff}header span{font-size:.875rem}a{color:inherit;font-weight:750;display:inline-flex;align-items:center;min-height:48px;padding:10px 0}main{max-width:560px;margin:auto;background:#fbf7ef}.intro,section,footer{padding:24px}.intro{padding-top:28px}h1{font-size:2.25rem;line-height:1.1;margin:16px 0}h2{font-size:1.7rem;line-height:1.2;margin:8px 0 16px}.logo{padding:4px;background:#00405a;border-radius:12px}.eyebrow{font-size:.875rem;letter-spacing:.06em;font-weight:750}nav{display:grid;gap:8px;margin:18px 0}nav a{border:1px solid #9eafb4;border-radius:12px;padding:12px 16px;text-decoration:none;background:#fff}label{display:block;font-weight:750;margin-top:20px}input{width:100%;font:inherit;padding:14px;border:1px solid #647d89;border-radius:10px;background:#fff;color:inherit}.step{border-top:2px solid #d9cfbd}.illustration{display:block;width:100%;height:220px;object-fit:contain;margin:16px 0}li{padding-left:6px;margin-bottom:16px}ol{padding-left:26px}.note{padding:16px;background:#eadcc5;border-radius:12px;font-weight:650}table{border-collapse:collapse;width:100%;margin:20px 0;font-size:1rem}td,th{border:1px solid #9eafb4;padding:10px;text-align:left}th{background:#00405a;color:#fff}details{padding:12px 0;border-bottom:1px solid #9eafb4}summary{font-weight:750;min-height:48px;padding:12px 0;cursor:pointer}footer a{display:flex}a.primary{background:#00405a;color:#fff;padding:14px 18px;border-radius:12px;justify-content:center;text-align:center;text-decoration:none;margin:16px 0}:focus-visible{outline:3px solid #946914;outline-offset:3px}[hidden]{display:none!important}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}'''
 (d/'online.css').write_text(css)
 (d/'online.js').write_text('''(() => {'use strict';const input=document.getElementById('busca'),status=document.getElementById('searchStatus'),items=[...document.querySelectorAll('.searchable')];const normalize=s=>s.normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').toLowerCase();function filter(){const q=normalize(input.value.trim());let n=0;items.forEach(el=>{const match=!q||normalize(el.textContent).includes(q);el.hidden=!match;if(match)n++;if(el.tagName==='DETAILS')el.open=Boolean(q&&match);});status.hidden=!q;status.textContent=n?`${n} tópicos encontrados. Veja abaixo.`:'Nenhum tópico encontrado. Tente outra palavra ou apague a busca.';}input.addEventListener('input',filter);document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',()=>{if(input.value){input.value='';filter();}}));})();''')
if __name__=='__main__':build_online(Path(sys.argv[1]))
